# Κάνοντας compile το <foo>_test.cpp με μια υλοποίηση <foo>.cpp του
# συγκεκριμένου τύπου, παράγουμε ένα test για την υλοποίηση αυτή.

mysh_OBJS = main.o helper_fun.o\
			myshell/run.o myshell/custom_commands.o myshell/init_constants.o myshell/redirection.o myshell/signal_handling.o\
			myshell/pipe.o myshell/wildcards.o myshell/alias.o myshell/tokenizer.o myshell/history.o

# Ο βασικός κορμός του Makefile
include ../common.mk
